### PR TITLE
Update Bluez5 to 5.63 version. JB#56721

### PR DESCRIPTION
**Pull request by ikamaletdinov**
Hello, This is update to version 5.63 and few commits backported from current master to make is stable.

I have made internal testing and seems that everything works fine.

Dropped commits after merge + rebase:
>> backport: build: Create directory for ell/useful.h --> it is backport and we will already have correct version in new revision
>> sfos: Add argument for defining which phonebook implementation to use. --> Changes from it also now presents in upstream

New introduced changes:
backport: profiles: Fix the reusing gerror without re-initialization
backport: device: Fix the reusing gerror without re-initialization
backport: adapter: Fix the reusing gerror without re-initialization
backport: device: Fix crash when removing device
backport: adapter: Fix crash when storing link key
backport: device: Fix device can't be scanned for 5 mins after reboot
backport: adv_monitor: Fix spamming errors
sfos: Bump version to 5.63 and update build requirements. JB#56721

Please note that now we need additional dependency to build bluez5 - python3-docutils, cause documentation is always generated from .rst files since version 5.59.

### CODE REVIEW

**Comment by mlehtima** [comment]
Instead of adding a new dependency it would make more sense to disable the man pages completely by using "--disable-manpages" configure option and removing the doc packaging since those are not often needed and the man pages can be easily found online if needed.

**Comment by ikamaletdinov** [comment]
> Instead of adding a new dependency it would make more sense to disable the man pages completely by using "--disable-manpages" configure option and removing the doc packaging since those are not often needed and the man pages can be easily found online if needed.

Sure, I've done that. Thanks for the review!

**Review by jusa — CHANGES_REQUESTED** [review]
You could squash

sfos: Enable NFC pairing
sfos: Allow D-Bus activation only through systemd
sfos: Don't rename bluez.pc to bluez5.spec
sfos: Disable manpages building. JB#56721
sfos: Bump version to 5.63. JB#56721

to "sfos: Add packaging.", you can add the content as mentions to the packaging commit.

**Comment by ikamaletdinov** [comment]
> You could squash
> 
> sfos: Enable NFC pairing sfos: Allow D-Bus activation only through systemd sfos: Don't rename bluez.pc to bluez5.spec sfos: Disable manpages building. JB#56721 sfos: Bump version to 5.63. JB#56721
> 
> to "sfos: Add packaging.", you can add the content as mentions to the packaging commit.

@jusa Thanks a lot for the review! I have squashed proposed commits. Seems that now history is cleaner. Please review again!

**Review by mlehtima — APPROVED** [review]

**Review by jusa — APPROVED** [review]

**Pull request merged**
